apiVersion: v1
kind: Pod
metadata:
  name: research-ai-dev
spec:
  containers:
    - name: surf-heartbeat
      image: docker.io/library/alpine:latest
      envFrom:
        - configMapRef:
            name: research-ai-env
      volumeMounts:
        - name: heartbeat-script-file
          mountPath: /scripts/surf-heartbeat.sh
          readOnly: true
      command: ["sh", "-c", "tr -d '\\r' < /scripts/surf-heartbeat.sh | sh"]

    - name: api
      image: research-ai-backend:dev
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONPATH
          value: "/app:/repo"
      envFrom:
        - configMapRef:
            name: research-ai-env
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: backend-src
          mountPath: /app
        - name: shared-src
          mountPath: /repo/shared
      command: ["bash", "-lc"]
      args:
        - |
          exec uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    - name: frontend
      image: docker.io/library/node:20-alpine
      workingDir: /app
      envFrom:
        - configMapRef:
            name: research-ai-env
      ports:
        - containerPort: 5173
      volumeMounts:
        - name: frontend-src
          mountPath: /app
        - name: frontend-node-modules
          mountPath: /app/node_modules
      command: ["sh", "-lc"]
      args:
        - |
          npm install
          exec npm run dev -- --host 0.0.0.0 --port 5173

    - name: caddy
      image: docker.io/library/caddy:2-alpine
      ports:
        - containerPort: 80
          hostPort: 8080
          hostIP: 127.0.0.1
      volumeMounts:
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /config
        - name: caddyfile-dev
          mountPath: /etc/caddy/Caddyfile
          readOnly: true

  volumes:
    - name: heartbeat-script-file
      hostPath:
        path: ./kube/surf-heartbeat.sh
        type: File

    - name: backend-src
      hostPath:
        path: ./backend
        type: Directory

    - name: shared-src
      hostPath:
        path: ./shared
        type: Directory

    - name: frontend-src
      hostPath:
        path: ./frontend
        type: Directory

    - name: frontend-node-modules
      persistentVolumeClaim:
        claimName: research-ai-modules-pvc

    - name: caddy-data
      hostPath:
        path: ./.caddy/data
        type: DirectoryOrCreate

    - name: caddy-config
      hostPath:
        path: ./.caddy/config
        type: DirectoryOrCreate

    - name: caddyfile-dev
      hostPath:
        path: ./kube/Caddyfile.dev
        type: File
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: research-ai-modules-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
