apiVersion: v1
kind: Pod
metadata:
  name: research-ai-prod
spec:
  containers:
    - name: surf-heartbeat
      image: docker.io/library/alpine:latest
      envFrom:
        - configMapRef:
            name: research-ai-env
      volumeMounts:
        - name: heartbeat-script-file
          mountPath: /scripts/surf-heartbeat.sh
          readOnly: true
      command: ["sh", "/scripts/surf-heartbeat.sh"]

    - name: api
      image: research-ai-backend:prod
      ports:
        - containerPort: 8000
          hostPort: 8000
          hostIP: 127.0.0.1
      envFrom:
        - configMapRef:
            name: research-ai-env

    - name: frontend
      image: research-ai-frontend:prod
      ports:
        - containerPort: 80
          hostPort: 3000
          hostIP: 127.0.0.1

  volumes:
    - name: heartbeat-script-file
      hostPath:
        path: /home/lvandee/Research-AI/kube/surf-heartbeat.sh
        type: File
