apiVersion: v1
kind: Pod
metadata:
  name: research-ai-dev
spec:
  containers:
    - name: api
      image: research-ai-api:dev
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FORCE_COLOR
          value: "1"
      envFrom:
        - configMapRef:
            name: research-ai-env
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: api-src
          mountPath: /work
      command: ["bash", "-lc"]
      args:
        - |
          exec uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    - name: frontend
      image: docker.io/library/node:20-alpine
      workingDir: /work
      env:
        - name: FORCE_COLOR
          value: "1"
      envFrom:
        - configMapRef:
            name: research-ai-env
      ports:
        - containerPort: 5173
      volumeMounts:
        - name: frontend-src
          mountPath: /work
        - name: frontend-node-modules
          mountPath: /work/node_modules
      command: ["sh","-lc"]
      args:
        - |
          npm install
          exec npm run dev -- --host 0.0.0.0 --port 5173

    - name: caddy
      image: docker.io/library/caddy:2-alpine
      ports:
        - containerPort: 80
          hostPort: 8080
          hostIP: 127.0.0.1
        - containerPort: 443
          hostPort: 8443
          hostIP: 127.0.0.1
      volumeMounts:
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /config
        - name: caddyfile-dev
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile.dev
          readOnly: true

  volumes:
    - name: api-src
      hostPath:
        path: ./api
        type: Directory

    - name: frontend-src
      hostPath:
        path: ./frontend
        type: Directory

    - name: frontend-node-modules
      persistentVolumeClaim:
        claimName: research-ai-modules-pvc

    - name: caddy-data
      hostPath:
        path: ./.caddy/data
        type: DirectoryOrCreate

    - name: caddy-config
      hostPath:
        path: ./.caddy/config
        type: DirectoryOrCreate

    - name: caddyfile-dev
      hostPath:
        path: ./caddy
        type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: research-ai-modules-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi