apiVersion: v1
kind: Pod
metadata:
  name: research-ai-prod
spec:
  containers:
    - name: api
      image: research-ai-backend:prod
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONPATH
          value: "/app"
      envFrom:
        - configMapRef:
            name: research-ai-env
      ports:
        - containerPort: 8000
          hostPort: 8000
          hostIP: 127.0.0.1

    - name: frontend
      image: research-ai-frontend:prod
      envFrom:
        - configMapRef:
            name: research-ai-env
      ports:
        - containerPort: 80
          hostPort: 3000
          hostIP: 127.0.0.1
