apiVersion: v1
kind: Pod
metadata:
  name: research-ai-prod
spec:
  containers:
    - name: api
      image: research-ai-api:prod
      envFrom:
        - configMapRef:
            name: research-ai-env

    - name: frontend
      image: research-ai-frontend:prod
      ports:
        - containerPort: 80
          hostPort: 8080
        - containerPort: 443
          hostPort: 8443
      volumeMounts:
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /config

  volumes:
    - name: caddy-data
      persistentVolumeClaim:
        claimName: caddy-data-pvc
    - name: caddy-config
      persistentVolumeClaim:
        claimName: caddy-config-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
