apiVersion: v1
kind: Pod
metadata:
  name: research-ai-prod
spec:
  containers:
    - name: api
      image: research-ai-backend:prod
      ports:
        - containerPort: 8000
          hostPort: 8000
          hostIP: 127.0.0.1
      envFrom:
        - configMapRef:
            name: research-ai-env

    - name: frontend
      image: research-ai-frontend:prod
      ports:
        - containerPort: 80
          hostPort: 3000
          hostIP: 127.0.0.1
